name: 'snowflake_utils'
version: '0.4.0'

config-version: 2

require-dbt-version: ">=1.3.0"

target-path: "target"
clean-targets: ["target", "dbt_modules"]
test-paths: ["test"]
macro-paths: ["macros"]
log-path: "logs"
