name: 'snowflake_utils'
version: '0.2.0'

config-version: 2

require-dbt-version: ">=0.17.0"

source-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
test-paths: ["test"]
macro-paths: ["macros"]
log-path: "logs"
